Description: "AWS CloudFormation template for deploying kubernetes cluster in AWS EKS"

Parameters:
  clusterRoleArn:
    Type: "String"
    Description: "AWS IAM Role to allow access to other AWS resources to operate clusters managed by EKS."
  securityGroupIds:
    Type: "List<AWS::EC2::SecurityGroup::Id>"
    Description: "Existing security group Ids"
  subnetIds:
    Type: "List<AWS::EC2::Subnet::Id>"
  nodeRoleArn:
    Type: "String"
    Description: "AWS IAM Role to allow access to other AWS resources to operate clusters managed by EKS."

Resources:
  mycluster:
      Type: AWS::EKS::Cluster
      Properties:
        Name: testcluster
        RoleArn: !Ref clusterRoleArn
        ResourcesVpcConfig:
          SecurityGroupIds: !Ref securityGroupIds
          SubnetIds: !Ref subnetIds
          EndpointPublicAccess: true
          EndpointPrivateAccess: true
  jenkins_controller_nodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: testcluster
      NodeRole: !Ref nodeRoleArn
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 1
      Subnets: !Ref subnetIds
      Labels: jenkins_controller
      AmiType: "AL2_x86_64"
      CapacityType: "ON_DEMAND"
      DiskSize: 8
      InstanceTypes: "t3a.micro"
  jenkins_agent_nodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: testcluster
      NodeRole: !Ref nodeRoleArn
      ScalingConfig:
        MinSize: 0
        DesiredSize: 1
        MaxSize: 1
      Subnets: !Ref subnetIds
      Labels: jenkins_agent
      AmiType: "AL2_x86_64"
      CapacityType: "ON_DEMAND"
      DiskSize: 8
      InstanceTypes: "t3a.small"


Outputs:
  clustreendpointurl:
    Value: !GetAtt mycluster.Endpoint
    Description: "Kubernetes API Server Url"
